service: sls-py-req-test

provider:
  name: aws
  runtime: python3.6
  #deploymentBucket: sls-py-req-test

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    zip: false
    cleanupZipHelper: true
    dockerizePip: false

package:
  exclude:
    - '**/*'
  include:
    - handler.py

functions:
  hello:
    handler: handler.hello
