version: '{build}'
init:
- ps: >-
    Install-Product node 6

    npm i -g serverless
build: off
test_script:
- cmd: >-
    cd example

    npm i

    sls package --pythonBin=c:/python36/python.exe