version: 2
jobs:
  build:
    working_directory: /sls-py-req
    docker:
      - image: ubuntu:rolling
    steps:
      - checkout
      # update pkg cache
      - run: apt -y update
      # install python3.6
      - run: apt -y install python3.6
      # install nodejs
      - run: apt -y install wget
      - run: wget -qO- https://deb.nodesource.com/setup_6.x | bash -
      - run: apt -y install nodejs
      # install serverless
      - run: npm install -g serverless
      # install test deps (this plugin)
      - run: cd example && npm i
      # try to package!
      - run: cd example && sls package
